name: CIFlutter

on:
  push:
    branches: master

steps:
- uses: actions/checkout@v2
- uses: subosito/flutter-action@v2
  with:
    channel: 'master' # or: 'beta' or 'master'
- run: flutter --version
